#if !defined(__BN3MONKEY_LIBRARY_INTERFACE_GENERATOR_KOTLINTYPECONVERTER_KT__)
#define __BN3MONKEY_LIBRARY_INTERFACE_GENERATOR_KOTLINTYPECONVERTER_KT__
static constexpr char* KOTLINTYPECONVERTER_KT = 
"interface WrapperTypeEnum\n"
"{\n"
"    fun toWrapperType() : Int\n"
"}\n"
"\n"
"inline fun <reified T : WrapperTypeEnum> toKotlinWrapperType(value : T) : Int {\n"
"    return value.toWrapperType()\n"
"}\n"
"\n"
"@JvmName(\"toKotlinWrapperEnumArray\")\n"
"inline fun <reified T : WrapperTypeEnum> toKotlinWrapperType(value : Array<T>) : IntArray {\n"
"    return value.map { toKotlinWrapperType(it) }.toIntArray()\n"
"}\n"
"@JvmName(\"toKotlinWrapperEnumVector\")\n"
"inline fun <reified  T : WrapperTypeEnum> toKotlinWrapperType(value : MutableList<T>) : MutableList<Int> {\n"
"    return value.map { toKotlinWrapperType(it)}.toMutableList()\n"
"}\n"
"inline fun <reified T> toKotlinType(value : Int) : T where  T: Enum<T>, T:  WrapperTypeEnum {\n"
"    return enumValues<T>().find {\n"
"        toKotlinWrapperType(it) == value\n"
"    }!!\n"
"}\n"
"@JvmName(\"toKotlinEnumArray\")\n"
"inline fun <reified T> toKotlinType(value : IntArray) : Array<T>  where  T: Enum<T>, T:  WrapperTypeEnum{\n"
"    return value.map { toKotlinType<T>(it) }.toTypedArray()\n"
"}\n"
"@JvmName(\"toKotlinEnumVector\")\n"
"inline fun <reified T> toKotlinType(value : MutableList<Int>) : MutableList<T>  where  T: Enum<T>, T: WrapperTypeEnum {\n"
"    return value.map { toKotlinType<T>(it) }.toMutableList()\n"
"}\n"
"\n"
"\n"
"abstract class WrapperTypeObject constructor(protected val nativeHandle : NativeHandle) : AutoCloseable {\n"
"\n"
"    data class NativeHandle(var value : Long)\n"
"    init {\n"
"        require(nativeHandle.value != 0L)\n"
"    }\n"
"\n"
"    fun toWrapperType() : Long = nativeHandle.value\n"
"\n"
"    protected val releaser = { close() }\n"
"    override fun close() {\n"
"        if (0L != nativeHandle.value)\n"
"        {\n"
"            release(nativeHandle.value)\n"
"            nativeHandle.value = 0L\n"
"        }\n"
"    }\n"
"\n"
"    abstract fun release(value : Long)\n"
"}\n"
"\n"
"inline fun <reified T> toKotlinWrapperType(value : T) : Long where T : WrapperTypeObject {\n"
"    return value.toWrapperType()\n"
"}\n"
"@JvmName(\"toKotlinWrapperObjectArray\")\n"
"inline fun <reified T> toKotlinWrapperType(value : Array<T>) : LongArray where T : WrapperTypeObject  {\n"
"    return value.map { toKotlinWrapperType(it) }.toLongArray()\n"
"}\n"
"@JvmName(\"toKotlinWrapperObjectVector\")\n"
"inline fun <reified T> toKotlinWrapperType(value : MutableList<T>) : MutableList<Long> where T : WrapperTypeObject  {\n"
"    return value.map { toKotlinWrapperType(it) }.toMutableList()\n"
"}\n"
"\n"
"inline fun <reified T> toKotlinType(value : Long) : T  where T : WrapperTypeObject {\n"
"    val constructor = T::class.java.getDeclaredConstructor(WrapperTypeObject.NativeHandle::class.java)\n"
"    return constructor.newInstance(WrapperTypeObject.NativeHandle(value))\n"
"}\n"
"\n"
"@JvmName(\"toKotlinObjectArray\")\n"
"inline fun <reified T> toKotlinType(value : LongArray) : Array<T>  where T : WrapperTypeObject {\n"
"    return value.map { toKotlinType<T>(it) }.toTypedArray()\n"
"}\n"
"@JvmName(\"toKotlinObjectVector\")\n"
"inline fun <reified T> toKotlinType(value : MutableList<Long>) : MutableList<T>  where T : WrapperTypeObject {\n"
"    return value.map { toKotlinType<T>(it) }.toMutableList()\n"
"}\n";
#endif //__BN3MONKEY_LIBRARY_INTERFACE_GENERATOR_KOTLINTYPECONVERTER_KT__
