#if !defined(__BN3MONKEY_LIBRARY_INTERFACE_GENERATOR_TAG_HPP__)
#define __BN3MONKEY_LIBRARY_INTERFACE_GENERATOR_TAG_HPP__
static constexpr char* TAG_HPP = 
"#ifndef __BN3MONKEY_TAG__\n"
"#define __BN3MONKEY_TAG__\n"
"\n"
"#include <cstring>\n"
"#include <algorithm>\n"
"#include <cassert>\n"
"\n"
"namespace Bn3Monkey\n"
"{\n"
"\tconstexpr size_t TAG_SIZE = 32;\n"
"\t\n"
"\tstruct Bn3Tag\n"
"\t{\n"
"\t\tBn3Tag() {\n"
"\t\t\t// name is 0\n"
"\t\t}\n"
"\t\texplicit Bn3Tag(const char* value)\n"
"\t\t{\n"
"\t\t\tsize_t length = strlen(value);\n"
"\t\t\tif (length >= TAG_SIZE - 1)\n"
"\t\t\t\tlength = TAG_SIZE - 1;\n"
"\t\t\tstd::copy(value, value + length, name);\n"
"\t\t}\n"
"\t\texplicit Bn3Tag(const Bn3Tag& prefix, const char* value)\n"
"\t\t{\n"
"\t\t\tsize_t prefix_len = strlen(prefix.name);\n"
"\t\t\tsize_t length = strlen(value);\n"
"\t\t\tif (prefix_len + length >= TAG_SIZE - 1)\n"
"\t\t\t{\n"
"\t\t\t\tlength = TAG_SIZE - 1 - prefix_len;\n"
"\t\t\t}\n"
"\n"
"\t\t\tstd::copy(prefix.name, prefix.name + prefix_len, name);\n"
"\t\t\tstd::copy(value, value+ length, name + prefix_len);\n"
"\t\t}\n"
"\t\texplicit Bn3Tag(const char* value, const Bn3Tag& postfix)\n"
"\t\t{\n"
"\t\t\tsize_t postfix_len = strlen(postfix.name);\n"
"\t\t\tsize_t length = strlen(value);\n"
"\t\t\tif (postfix_len + length < TAG_SIZE - 1)\n"
"\t\t\t{\n"
"\t\t\t\tlength = TAG_SIZE - 1 - postfix_len;\n"
"\t\t\t}\n"
"\n"
"\t\t\tstd::copy(value, value + length, name);\n"
"\t\t\tstd::copy(postfix.name, postfix.name + postfix_len, name + length);\n"
"\t\t}\n"
"\t\tBn3Tag(const Bn3Tag& other)\n"
"\t\t{\n"
"\t\t\tconst char* value = other.name;\n"
"\t\t\tsize_t length = strlen(value);\n"
"\t\t\tstd::copy(value, value + length, name);\n"
"\t\t}\n"
"\t\tBn3Tag(Bn3Tag&& other) noexcept\n"
"\t\t{\n"
"\t\t\tconst char* value = other.name;\n"
"\t\t\tsize_t length = strlen(value);\n"
"\t\t\tstd::copy(value, value + length, name);\n"
"\t\t}\n"
"\t\tBn3Tag& operator=(const Bn3Tag& other)\n"
"\t\t{\n"
"\t\t\tclear();\n"
"\t\t\tconst char* value = other.name;\n"
"\t\t\tsize_t length = strlen(value);\n"
"\t\t\tstd::copy(value, value + length, name);\n"
"\n"
"\t\t\treturn *this;\n"
"\t\t}\n"
"\n"
"\t\tinline bool operator==(const Bn3Tag& other)\n"
"\t\t{\n"
"\t\t\treturn !strcmp(name, other.name);\n"
"\t\t}\n"
"\n"
"\t\tinline void clear() { memset(name, 0, sizeof(name)); }\n"
"\t\tinline const char* str() const { return name; }\n"
"\n"
"\tprivate:\n"
"\t\tchar name[TAG_SIZE]{ 0 };\n"
"\t};\n"
"}\n"
"\n"
"#endif\n";
#endif //__BN3MONKEY_LIBRARY_INTERFACE_GENERATOR_TAG_HPP__
